---
title: "Zebreg- Comparing distributions"
output: html_document
---

```{r libraries, echo=FALSE}

library(tidyverse)
library(ggpubr)
library(showtext)
showtext_auto()
#library(broom)
#library(nortest)
font_add("Trebuchet MS", "trebuc.ttf")
library(RColorBrewer)
library(ggpubr)
library(gridExtra)

```

```{r plot function}
colors <- brewer.pal(n = 12, name = "Set3")

gg_qq_empirical <- function(original , imputed , gene, color, quantiles = seq(0,1,0.01)){
   ggplot(mapping = aes(x = quantile((original), quantiles), 
                       y = quantile((imputed), quantiles))) + 
    geom_point(color = color) +
    geom_abline(aes(slope = 1, intercept = 0), linetype = 2) +
    labs(x = paste(gene, "(Original)"),
         y= paste(gene, "(Imputed)"))
}


base_family = "Trebuchet MS"
base_size = 60
```

```{r importing combined csv}
imputed_18ss <- read.csv("./datasets/merged_csv/18ss_combined.csv")

stt_posterior <- read.csv("./datasets/merged_csv/stt_posterior.csv")
colnames(stt_posterior)[1] <- "sample_no"
stt_posterior
sthc_posterior <- read.csv("./datasets/merged_csv/sthc_posterior.csv")
colnames(sthc_posterior)[1] <- "sample_no"

stsc_posterior <- read.csv("./datasets/merged_csv/stsc_posterior.csv")
colnames(stsc_posterior)[1] <- "sample_no"

sttc_posterior <- read.csv("./datasets/merged_csv/sttc_posterior.csv")
colnames(sttc_posterior)[1] <- "sample_no"

stti_posterior <- read.csv("./datasets/merged_csv/stti_posterior.csv")
colnames(stti_posterior)[1] <- "sample_no"

stwd_posterior <- read.csv("./datasets/merged_csv/stwd_posterior.csv")
colnames(stwd_posterior)[1] <- "sample_no"

stzc_posterior <- read.csv("./datasets/merged_csv/stzc_posterior.csv")
colnames(stzc_posterior)[1] <- "sample_no"

```

```{r extracting gene intensities}
### Sox2
sox2_18ss <- stt_posterior %>% 
  filter(sample_no == 2) %>%
  select("sox2")%>%
  filter(!(sox2 < median(sox2) - 3*mad(sox2) | sox2 > median(sox2) + 3*mad(sox2))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_sox2 <- imputed_18ss %>%
  select("Sox2")%>%
  filter(!(Sox2 < median(Sox2) - 3*mad(Sox2) | Sox2 > median(Sox2) + 3*mad(Sox2)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

# tbxta
tbxta_18ss <- stt_posterior %>% 
  filter(sample_no == 2) %>%
  select("tbxta") %>%
  filter(!(tbxta < median(tbxta) - 3*mad(tbxta) | tbxta > median(tbxta) + 3*mad(tbxta))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_tbxta <- imputed_18ss %>%
  select("Tbxta")%>%
  filter(!(Tbxta < median(Tbxta) - 3*mad(Tbxta) | Tbxta > median(Tbxta) + 3*mad(Tbxta)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

tcf_18ss <- stt_posterior %>% 
  filter(sample_no == 2) %>%
  select("TCF_mRNA_levels")%>%
  filter(!(TCF_mRNA_levels < median(TCF_mRNA_levels) - 3*mad(TCF_mRNA_levels) | TCF_mRNA_levels > median(TCF_mRNA_levels) + 3*mad(TCF_mRNA_levels))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_tcf <- imputed_18ss %>%
  select("TCF")%>%
  filter(!(TCF < median(TCF) - 3*mad(TCF) | TCF > median(TCF) + 3*mad(TCF)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

hes6_18ss <- sthc_posterior %>%
  filter(sample_no == 1) %>%
  select("hes6")%>%
  filter(!(hes6 < median(hes6) - 3*mad(hes6) | hes6 > median(hes6) +3*mad(hes6))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_hes6 <- imputed_18ss %>%
  select("Hes6")%>%
  filter(!(Hes6 < median(Hes6) - 3*mad(Hes6) | Hes6 > median(Hes6) + 3*mad(Hes6)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

cdh6_18ss <- stzc_posterior %>%
  filter(sample_no == 4) %>%
  select("cdh6")%>%
  filter(!(cdh6 < median(cdh6) - 3*mad(cdh6) | cdh6 > median(cdh6) + 3*mad(cdh6))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_cdh6<- imputed_18ss %>%
  select("Cdh6")%>%
  filter(!(Cdh6 < median(Cdh6) - 3*mad(Cdh6) | Cdh6 > median(Cdh6) + 3*mad(Cdh6)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)
  
sp5l_18ss <- stsc_posterior %>%
  filter(sample_no == 5) %>%
  select("sp5l")%>%
  filter(!(sp5l < median(sp5l) - 3*mad(sp5l) | sp5l > median(sp5l) + 3*mad(sp5l))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_sp5l<- imputed_18ss %>%
  select("Sp5l")%>%
  filter(!(Sp5l < median(Sp5l) - 3*mad(Sp5l) | Sp5l > median(Sp5l) + 3*mad(Sp5l)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)
  
tagln3b_18ss <- sttc_posterior %>%
  filter(sample_no == 3) %>%
  select("tagln3b")%>%
  filter(!(tagln3b < median(tagln3b) - 3*mad(tagln3b) | tagln3b > median(tagln3b) + 3*mad(tagln3b))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_tagln3b<- imputed_18ss %>%
  select("Tagln3b")%>%
  filter(!(Tagln3b < median(Tagln3b) - 3*mad(Tagln3b) | Tagln3b > median(Tagln3b) + 3*mad(Tagln3b)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

znf703_18ss <- stzc_posterior %>%
  filter(sample_no == 4) %>%
  select("znf703")%>%
  filter(!(znf703 < median(znf703) - 3*mad(znf703) | znf703 > median(znf703) + 3*mad(znf703))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_znf703<- imputed_18ss %>%
  select("Znf703")%>%
  filter(!(Znf703 < median(Znf703) - 3*mad(Znf703) | Znf703 > median(Znf703) + 3*mad(Znf703)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

wnt8a_18ss <- stwd_posterior %>%
  filter(sample_no == 1) %>%
  select("wnt8a")%>%
  filter(!(wnt8a < median(wnt8a) - 3*mad(wnt8a) | wnt8a > median(wnt8a) + 3*mad(wnt8a))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_wnt8a<- imputed_18ss %>%
  select("Wnt8a")%>%
  filter(!(Wnt8a < median(Wnt8a) - 3*mad(Wnt8a) | Wnt8a > median(Wnt8a) + 3*mad(Wnt8a)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

depdc7a_18ss <- stwd_posterior%>%
  filter(sample_no == 1) %>%
  select("depdc7a")%>%
  filter(!(depdc7a < median(depdc7a) - 3*mad(depdc7a) | depdc7a > median(depdc7a) + 3*mad(depdc7a))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_depdc7a<- imputed_18ss %>%
  select("Depdc7a")%>%
  filter(!(Depdc7a < median(Depdc7a) - 3*mad(Depdc7a) | Depdc7a > median(Depdc7a) + 3*mad(Depdc7a)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

thbs2_18ss <- stti_posterior %>%
  filter(sample_no == 1) %>%
  select("thbs2")%>%
  filter(!(thbs2 < median(thbs2) - 3*mad(thbs2) | thbs2 > median(thbs2) + 3*mad(thbs2))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_thbs2<- imputed_18ss %>%
  select("Thbs2")%>%
  filter(!(Thbs2 < median(Thbs2) - 3*mad(Thbs2) | Thbs2 > median(Thbs2) + 3*mad(Thbs2)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

id3_18ss <-stti_posterior %>%
  filter(sample_no == 1) %>%
  select("id3")%>%
  filter(!(id3 < median(id3) - 3*mad(id3) | id3 > median(id3) + 3*mad(id3))) %>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)

imputed_18ss_id3<- imputed_18ss %>%
  select("Id3")%>%
  filter(!(Id3 < median(Id3) - 3*mad(Id3) | Id3 > median(Id3) + 3*mad(Id3)))%>%
  lapply(as.numeric)%>%
  unlist(use.names = FALSE)


```

```{r qqplot}
base_size = 30
qq_tbxta <- gg_qq_empirical((tbxta_18ss), imputed_18ss_tbxta, "tbxta", "brown3")
qq_tbxta <- qq_tbxta + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_tbxta
ggsave("./results/qqplots/qq_tbxta.png", qq_tbxta)

qq_sox2 <- gg_qq_empirical((sox2_18ss), imputed_18ss_sox2, "sox2", "chartreuse3")
qq_sox2 <- qq_sox2 + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_sox2
ggsave("./results/qqplots/qq_sox2.png", qq_sox2)


qq_tcf <- gg_qq_empirical((tcf_18ss), imputed_18ss_tcf, "TCF", "cyan1")
qq_tcf<- qq_tcf + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_tcf
ggsave("./results/qqplots/qq_tcf.png", qq_tcf)


qq_hes6 <- gg_qq_empirical((hes6_18ss), imputed_18ss_hes6, "hes6", "brown1")
qq_hes6 <- qq_hes6  + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_hes6
ggsave("./results/qqplots/qq_hes6.png", qq_hes6)

qq_cdh6 <- gg_qq_empirical((cdh6_18ss), imputed_18ss_cdh6, "cdh6", "darkolivegreen3")
qq_cdh6 <- qq_cdh6 + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_cdh6
ggsave("./results/qqplots/qq_cdh6.png", qq_cdh6)

qq_wnt8a <- gg_qq_empirical((wnt8a_18ss), imputed_18ss_wnt8a, "wnt8a", "darkslategray3")
qq_wnt8a <- qq_wnt8a + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_wnt8a
ggsave("./results/qqplots/qq_wnt8a.png", qq_wnt8a)


qq_sp5l <- gg_qq_empirical((sp5l_18ss), imputed_18ss_sp5l, "sp5l", "darkorange1")
qq_sp5l <- qq_sp5l + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_sp5l
ggsave("./results/qqplots/qq_sp5l.png", qq_sp5l)


qq_znf703 <- gg_qq_empirical((znf703_18ss), imputed_18ss_znf703, "znf703", "deeppink1")
qq_znf703 <- qq_znf703 + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_znf703
ggsave("./results/qqplots/qq_znf703.png", qq_znf703)


qq_depdc7a <- gg_qq_empirical((depdc7a_18ss), imputed_18ss_depdc7a, "depdc7a", "blueviolet")
qq_depdc7a <- qq_depdc7a + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_depdc7a
ggsave("./results/qqplots/qq_depdc7a.png", qq_depdc7a)


qq_tagln3b <- gg_qq_empirical((tagln3b_18ss), imputed_18ss_tagln3b, "tagln3b", "coral")
qq_tagln3b <- qq_tagln3b + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_tagln3b
ggsave("./results/qqplots/qq_tagln3b.png", qq_tagln3b)


qq_id3 <- gg_qq_empirical((id3_18ss), imputed_18ss_id3, "id3", "deepskyblue3")
qq_id3 <- qq_id3 + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_id3
ggsave("./results/qqplots/qq_id3.png", qq_id3)


qq_thbs2 <- gg_qq_empirical((thbs2_18ss), imputed_18ss_thbs2, "thbs2", "deepskyblue")
qq_thbs2 <- qq_thbs2 + theme_bw(base_family = base_family, base_size = base_size) + coord_equal()
qq_thbs2
ggsave("./results/qqplots/qq_thbs2.png", qq_thbs2)


```
Comparing joint distributions of 2 genes:
- Sox2 and tbxta - stt, sample2
- Znf703 and Cdh6
- Sp5l and Cdh6


```{r Creating dataframes}

st_original_df <- stt_posterior %>%
  filter(sample_no == 2)
head(st_original_df)
st_original <- data.frame(sox2 = st_original_df$sox2, tbxta = st_original_df$tbxta, data = "Original")
st_imputed <- data.frame(sox2 = imputed_18ss$Sox2, tbxta = imputed_18ss$Tbxta, data = "Imputed")
st_merge <- rbind(st_original, st_imputed)

zc_original_df <- stzc_posterior %>%
  filter(sample_no == 4)
head(zc_original_df)
zc_original <- data.frame(Znf703 = zc_original_df$znf703, Cdh6 = zc_original_df$cdh6, data = "Original")
zc_imputed <- data.frame(Znf703 = imputed_18ss$Znf703, Cdh6 = imputed_18ss$Cdh6, data = "Imputed")
zc_merge <- rbind(zc_original, zc_imputed)

wd_original_df <- stwd_posterior %>%
  filter(sample_no == 1)
head(wd_original_df)
wd_original <- data.frame(Wnt8a = wd_original_df$wnt8a, Depdc7a = wd_original_df$depdc7a, data = "Original")
wd_imputed <- data.frame(Wnt8a = imputed_18ss$Wnt8a, Depdc7a = imputed_18ss$Depdc7a, data = "Imputed")
wd_merge <- rbind(wd_original, wd_imputed)


```

```{r Sox2 Tbxta ggplots}

p1 <- ggplot(data = st_merge, aes(x = sox2, y = tbxta, color = data))+
  geom_point(alpha = 0.15)+ 
  theme_bw(base_family = base_family)+
  theme(legend.title = element_blank(), legend.position =  c(0.85,0.85), legend.text = element_text(size = 10),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x = "Sox2", y = "Tbxta")
  
  
p2 <- ggplot(data = st_merge, aes(x=sox2, colour = factor(data), fill = factor(data)))+
  geom_density(alpha = 0.25) + 
  scale_x_continuous(breaks=NULL,expand=c(0.02,0)) +
  scale_y_continuous(breaks=NULL,expand=c(0.02,0)) + 
  theme_bw(base_family = base_family) +
  theme(legend.position = 'none', panel.border = element_blank())+
  labs(x = "", y = "")

p3 <- ggplot(data = st_merge, aes(x=tbxta, colour = factor(data), fill = factor(data)))+
  geom_density(alpha = 0.25) + 
  coord_flip()+
  scale_x_continuous(breaks=NULL,expand=c(0.02,0)) +
  scale_y_continuous(breaks=NULL,expand=c(0.02,0))+ 
  theme_bw(base_family = base_family)+
  theme(legend.position = 'none', panel.border = element_blank())+
  labs(x = "", y = "")

p4 <- grid.arrange(arrangeGrob(p2,ncol=2,widths=c(3,1)),
             arrangeGrob(p1,p3,ncol=2,widths=c(3,1.25)),
             heights=c(1,3))

ggsave("./results/scatterplots/sox2_tbxta.png", p4)

```


```{r Znf703 Cdh6 ggplots}

p1 <- ggplot(data = zc_merge, aes(x = Znf703, y = Cdh6, color = data))+
  geom_point(alpha = 0.15)+ 
  theme_bw(base_family = base_family)+
  theme(legend.title = element_blank(), legend.position =  c(0.85,0.85), legend.text = element_text(size = 10),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x = "Znf703", y = "Cdh6")
  
  
p2 <- ggplot(data = zc_merge, aes(x=Znf703, colour = factor(data), fill = factor(data)))+
  geom_density(alpha = 0.25) + 
  scale_x_continuous(breaks=NULL,expand=c(0.02,0)) +
  scale_y_continuous(breaks=NULL,expand=c(0.02,0)) + 
  theme_bw(base_family = base_family) +
  theme(legend.position = 'none', panel.border = element_blank())+
  labs(x = "", y = "")

p3 <- ggplot(data = zc_merge, aes(x=Cdh6, colour = factor(data), fill = factor(data)))+
  geom_density(alpha = 0.25) + 
  coord_flip()+
  scale_x_continuous(breaks=NULL,expand=c(0.02,0)) +
  scale_y_continuous(breaks=NULL,expand=c(0.02,0))+ 
  theme_bw(base_family = base_family)+
  theme(legend.position = 'none', panel.border = element_blank())+
  labs(x = "", y = "")

p4 <- grid.arrange(arrangeGrob(p2,ncol=2,widths=c(3,1)),
             arrangeGrob(p1,p3,ncol=2,widths=c(3,1.25)),
             heights=c(1,3))

ggsave("./results/scatterplots/znf703_cdh6.png", p4)


```

```{r Wnt8a Depdc7a ggplots}

p1 <- ggplot(data = wd_merge, aes(x = Wnt8a, y = Depdc7a, color = data))+
  geom_point(alpha = 0.15)+ 
  theme_bw(base_family = base_family)+
  theme(legend.title = element_blank(), legend.position =  c(0.85,0.85), legend.text = element_text(size = 10),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x = "Wnt8a", y = "Depdc7a")
  
  
p2 <- ggplot(data = wd_merge, aes(x=Wnt8a, colour = factor(data), fill = factor(data)))+
  geom_density(alpha = 0.25) + 
  scale_x_continuous(breaks=NULL,expand=c(0.02,0)) +
  scale_y_continuous(breaks=NULL,expand=c(0.02,0)) + 
  theme_bw(base_family = base_family) +
  theme(legend.position = 'none', panel.border = element_blank())+
  labs(x = "", y = "")

p3 <- ggplot(data = wd_merge, aes(x=Depdc7a, colour = factor(data), fill = factor(data)))+
  geom_density(alpha = 0.25) + 
  coord_flip()+
  scale_x_continuous(breaks=NULL,expand=c(0.02,0)) +
  scale_y_continuous(breaks=NULL,expand=c(0.02,0))+ 
  theme_bw(base_family = base_family)+
  theme(legend.position = 'none', panel.border = element_blank())+
  labs(x = "", y = "")

p4 <- grid.arrange(arrangeGrob(p2,ncol=2,widths=c(3,1)),
             arrangeGrob(p1,p3,ncol=2,widths=c(3,1.25)),
             heights=c(1,3))

ggsave("./results/scatterplots/wnt8a_depdc7a.png", p4)


```



